spring:
  application:
    name: EHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehub
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9595