spring:
  application:
    name: EHub
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
server:
  port: 9595
  tomcat:
    max-http-form-post-size: 100000000